[project]
name = "llm-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.116.2",
    "litellm>=1.77.1",
    "logfire[fastapi,litellm,system-metrics]>=4.8.0",
    "loguru>=0.7.3",
]
